name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
  pull_request:
    branches:
      - development

jobs:
  # UPDATE TO THE MODULE REPO SO PR'S CAN REUSE IT
  tests:
    uses: coldbox-modules/cbNameCheap/.github/workflows/tests.yml@development
